### ISSUE TITLE
Wrong certificate for https://seiyria.com

### ISSUE THREAD

**Issue by viceice** [seiyria/seiyria.github.io#1]
Hi,

You should check yout repository settings. The SSL-Certificate ist only valid for *.github.io.
It should be include yout custom domain.

Regards
Michael

**Comment by seiyria** [comment]
Thanks, but GitHub doesn't let me control what's in the cert.

**Comment by viceice** [comment]
See [here](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/). With that you should get an lets encrypt cert wich would be valid for your custom domain.

**Comment by seiyria** [comment]
Here's what I don't understand, though. It shows I have a cert for my site:

![image](https://user-images.githubusercontent.com/763609/46807346-50f21700-cd2f-11e8-8527-199f003ac31f.png)

I have used the "enforce HTTPS" checkbox but every time I do that, someone complains that they get infinite redirects. I never can reproduce it. In any case, I've toggled on the checkbox, but I don't know how long it takes to go into effect, so hopefully it works.

**Comment by viceice** [comment]
Looks like you have to update your [A Records](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider)

**Comment by viceice** [comment]
They should be 

```
185.199.108.153
185.199.109.153
185.199.110.153
185.199.111.153
```

actual:
```
Name:    seiyria.com
Addresses:  185.199.108.153
          192.30.252.153
          192.30.252.154
```

**Comment by seiyria** [comment]
Alright. I've done that. Not sure why I had old A records in there.

**Comment by viceice** [comment]
Now it's working for me. Thanks. 👍

**Comment by seiyria** [comment]
thank you!
